https://qyapi.weixin.qq.com/cgi-bin/user/get_active_stat?access_token=qOsCAU10Ce5oEdwZP9bjndw7tMn0zs4lKr8lp9iUEUWnRyYUtqAeD650NLjSJ44lRvELoRMHKKVAh29JZv3R9pJ1dxekM0TEEBF16lGHxSl6HU1Z5kxmPRJFNFG9YkSwxGAAmiJW7lvsVUF48RRI7Eo7HihavL8n25t2-mkIOPLLk0ibj6AjyPDpB0VhvqGl3LwgHx-FWO76XmTEg5ge8Q
Content-Type: application/json

{
  "date": "2021-07-01"
}
###
